name: Security Analysis Example

on:
  # Manually trigger the workflow
  workflow_dispatch:
  
  # Run on push to main branch (optional)
  # push:
  #   branches: [ main ]
  
  # Run on pull requests (optional)
  # pull_request:
  #   branches: [ main ]
  
  # Schedule regular scans (optional)
  # schedule:
  #   - cron: '0 0 * * 0'  # Weekly at midnight on Sunday

jobs:
  analyze:
    runs-on: ubuntu-latest
    name: Analyze Repository Security
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Alder AI Security Agent
        uses: adamsmith6300/alder-gha@v1.0.2
        with:
          api-key: ${{ secrets.ALDER_API_KEY }}  # Required API key
          extra-ignore-dirs: 'dist,tmp,docs' # Optional: comma-separated list of extra directories to ignore

      - name: Upload security reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: './security-reports'

